### ISSUE TITLE
//Learn

### ISSUE THREAD

**Issue by EnforcerRyan** [JsKingBoo/SableyeBot3#18] opened 2020-06-29 15:45 UTC
The //learn command gives what we've narrowed down to be a learnset for Lucario for every Pokemon we tested. Blastoise, Pikachu, Lucario and Zeraora were tested. They all gave the same result. We first noticed when it said Blastoise learns Blaze Kick

**Comment by Stalruth** [comment] 2020-06-30 10:28
I've looked into this. My latest commit should fix this issue, but the bot needs rebooting and I can't do that.

I'll quickly check and get back to you.

**Comment by Stalruth** [comment] 2020-06-30 10:34
Yep, the issue is fixed in the latest update (commit fbd98d7d9484ead4301a40414e5cd07e2e9951cb); we're just waiting on it going live.

Thanks for the report, there might still be other things wrong (as PS changed a lot of internals that we plug into between our last update and IoA) so don't hesitate to let us know of any other issues you have.

**Closed as completed by Stalruth** 2020-06-30 10:34 UTC
